				cout<<endl;
    			cout<<left<<"Statystyki";
    			cout.width(30);
    			cout<<right<<"Opis"<<endl<<endl;
    			cout<<left<<"Sila ";
				cout.width(4);
				cout<<left<<sila;
    			cout.width(26);
    			cout<<" ";
    			cout<<left<<" Dupeweqweqwerweqrewqrweqrweqrweqrewqrewqrewqrqwerew"<<endl;
				cout<<left<<"Zrecznosc ";
				cout.width(4);
				cout<<left<<zrecznosc;
    			cout.width(22);
    			cout<<" ";
    			cout<<left<<"Blaewqeeqlaqwereqwrweqrwerweqrweqrewqrwqe"<<endl;
				cout<<left<<"Zywotnosc ";
				cout.width(4);
				cout<<left<<zywotnosc;
    			cout.width(22);
    			cout<<" ";
    			cout<<left<<"Blallaeeelalaeweqweeqweeqlawqerewqrewqrrweqrewqrweqrweqrweqw"<<endl;
				cout<<right<<"Energia ";
				cout.width(4);
				cout<<left<<energia;
    			cout.width(24);
    			cout<<" ";
    			cout<<left<<"Beqlrwqerewqrweqrweqrwqerqwerweqra"<<endl;
				cout<<right<<"Obrona ";
				cout.width(4);
				cout<<left<<obrona;
    			cout.width(25);
    			cout<<" ";
    			cout<<left<<"Beeeeeeeeeqlaqwerqwerweqrweqrweqrqwerqweeqwrweqr"<<endl;
				cout<<right<<"Zycie ";
				cout.width(4);
				cout<<left<<zycie_max;
    			cout.width(26);
    			cout<<" ";
    			cout<<left<<"Beeeeeeeeeqlawqerewqrewqrweqr"<<endl;
				cout<<right<<"Mana ";
				cout.width(4);
				cout<<left<<mana_max;
    			cout.width(27);
    			cout<<" ";
    			cout<<right<<"Beeeeeeeeeqrweqrweqra"<<endl;